name: Golang

on:
  push:
    paths:
      - .github/workflows/go.yml
      - go/**

defaults:
  run:
    working-directory: go

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - run: go test ./...
        name: Run tests

      - run: go get -t -v github.com/avito-tech/go-mutesting/...
        name: Install Go MuTesting
        
      - run: go-mutesting ./...
        name: Run mutation testing tool