name: Pipeline Linting

on:
  push:
    paths:   
      - .github/workflows/**
  pull_request:
    paths:   
      - .github/workflows/**

jobs:
  lint:
    concurrency:
      group: ci-lint-pipeline-${{ github.ref }}
      cancel-in-progress: true
    uses: armakuni/github-actions/.github/workflows/lint-pipeline.yml@cee3c433194a2e9ba4566d3423e4454f36fb97d0 # v0.19.3
