name: Python

on:
  push:
    paths:
      - .github/workflows/python.yml
      - python/**

defaults:
  run:
    working-directory: python

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Just
      uses: extractions/setup-just@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
    - name: Install uv
      run: |
        just install-uv
    - name: Set up virtual environment with uv
      run: |
        uv venv
    - name: Install dependencies
      run: |
        source .venv/bin/activate
        uv pip install pytest cosmic-ray
    - name: Run tests
      run: |
        source .venv/bin/activate
        just test
    - name: Run before-mutants
      run: |
        source .venv/bin/activate
        just before-mutants
    - name: Run after-mutants
      run: |
        source .venv/bin/activate
        just after-mutants
    - name: Generate mutation test report
      run: |
        source .venv/bin/activate
        just generate-report
    - name: Upload mutation test report
      uses: actions/upload-artifact@v3
      with:
        name: mutation-test-report
        path: python/report.html
